#!/bin/bash
if [ $# -ge 1 ]
then
	if [ $1 = "-sort" ]
	then
		/opt/Clearing-File-name/sort_series.php "$2"
		exit
	fi
	if [ $1 = "-clear" ]
	then
		/opt/Clearing-File-name/clear_name.php "$2"
		exit
	fi
fi
/opt/Clearing-File-name/clear_name.php "$1"
/opt/Clearing-File-name/sort_series.php "$1"
